Sundsvallskommun/dept44

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-resttemplate/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

Update of pom.xml to release to maven central and release of v1.26 performed.

Uf 3947 release

---

dept44-starter/src/main/java/se/sundsvall/dept44/configuration/SecurityConfiguration.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/SecurityConfigurationTest.java

UF-4351 - Re-enable CSRF

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-1.31

PR for release  release-1.31

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-1.32

PR for release  release-1.32

---

dept44-starter/src/main/java/se/sundsvall/dept44/logbook/filter/BodyFilterProvider.java
dept44-starter/src/test/java/se/sundsvall/dept44/logbook/filter/BodyFilterProviderTest.java
dept44-starter/src/test/resources/json-path-filter.expected.json
dept44-starter/src/test/resources/json-path-filter.input.json

Fixes Logbook JsonPath filtering

UF-4694 - Logbook JsonPath filtering

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-1.33

PR for release  release-1.33

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-1.35

PR for release  release-1.35

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-2.0.0

PR for release  release-2.0.0

---

dept44-service-parent/pom.xml

Disables Java 17 preview features

UF-5038 - Disable Java 17 preview features

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-2.0.1

PR for release  release-2.0.1

---

dept44-build-tools/pom.xml
dept44-build-tools/src/main/java/se/sundsvall/dept44/maven/enforcer/rule/Dept44RequiredPropertiesRule.java
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-example/src/main/resources/application-it.properties
dept44-example/src/main/resources/application-junit.properties
dept44-example/src/test/java/se/sundsvall/petinventory/integration/db/SchemaVerificationTest.java
dept44-example/src/test/resources/db/scripts/schema.sql
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-feign/src/main/java/se/sundsvall/dept44/configuration/feign/decoder/AbstractErrorDecoder.java
dept44-starter-feign/src/main/java/se/sundsvall/dept44/configuration/feign/decoder/JsonPathErrorDecoder.java
dept44-starter-feign/src/main/java/se/sundsvall/dept44/configuration/feign/decoder/ProblemErrorDecoder.java
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
dept44-starter/src/main/java/se/sundsvall/dept44/exception/ClientProblem.java
dept44-starter/src/main/java/se/sundsvall/dept44/exception/ServerProblem.java
pom.xml

Bumps Spring Boot to 3.1 and bumps the dept44 version to 2.1.0

UF-5253 - Upgrade to Spring Boot 3.1

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-2.1.0

PR for release  release-2.1.0

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-2.1.1

PR for release  release-2.1.1

---

pom.xml

UF-XYZ - Bump Spring Boot to 3.1.1

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-1.36

PR for release  release-1.36

---

dept44-example/src/test/java/se/sundsvall/petinventory/integration/db/model/PetNameEntityTest.java
dept44-starter-feign/src/main/java/se/sundsvall/dept44/configuration/feign/FeignConfiguration.java
dept44-starter-feign/src/test/java/se/sundsvall/dept44/configuration/feign/FeignConfigurationTest.java

Corrected configuration issue with duplicated feign.Logger-beans due to new Logbook-version.

UF-5571: Fix Loggbok issue

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-2.1.2

PR for release  release-2.1.2

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-2.1.3

PR for release  release-2.1.3

---

dept44-starter/src/main/java/se/sundsvall/dept44/configuration/SecurityConfiguration.java

https://spring.io/security/cve-2023-34035

uf-5772: fixed vulnerability issue regarding requestMatchers

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-2.1.4

PR for release  release-2.1.4

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-3.0

PR for release  release-3.0

---

dept44-common-validators/src/main/java/se/sundsvall/dept44/common/validators/annotation/OneOf.java
dept44-common-validators/src/main/java/se/sundsvall/dept44/common/validators/annotation/impl/OneOfConstraintValidator.java
dept44-common-validators/src/test/java/se/sundsvall/dept44/common/validators/annotation/impl/OneOfConstraintValidatorTest.java

Adds a custom validator for ensuring that a value exists in a pre-defined list of allowed values

UF-5979 - OneOf validator

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-3.1

PR for release  release-3.1

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-3.2

PR for release  release-3.2

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-3.3

PR for release  release-3.3

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-3.4

PR for release  release-3.4

---

dept44-example/pom.xml
dept44-example/src/main/java/se/sundsvall/petinventory/api/PetInventoryResource.java
pom.xml

* Make openapi-generator-maven-plugin a managed dependency.
* Fix issues in example service: image binary content was logged (Fixed by adding CONTENT_DISPOSITION-header)

UF-6363: Make openapi-generator-maven-plugin a managed dependency.

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-1.37

PR for release  release-1.37

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-4.1

PR for release  release-4.1

---

dept44-starter-feign/src/main/java/se/sundsvall/dept44/configuration/feign/decoder/AbstractErrorDecoder.java
dept44-starter-feign/src/main/java/se/sundsvall/dept44/configuration/feign/decoder/ProblemErrorDecoder.java
dept44-starter-feign/src/main/java/se/sundsvall/dept44/configuration/feign/decoder/util/ProblemUtils.java
dept44-starter-feign/src/test/java/se/sundsvall/dept44/configuration/feign/decoder/ProblemErrorDecoderTest.java
dept44-starter-feign/src/test/java/se/sundsvall/dept44/configuration/feign/decoder/util/ProblemUtilsTest.java
dept44-starter-feign/src/test/resources/constraintViolationProblem.json
dept44-starter-feign/src/test/resources/minimalProblem.json
dept44-starter-feign/src/test/resources/problem.json

Add support for ConstraintViolationProblems in ProblemErrorDecoder.
All violations will be populated in the details-attribute.

Uf 6708 support for constraintviolations inproblem error decoder

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

UF-6722: Switch to SemVer

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-4.2.0

PR for release  release-4.2.0

---

.github/dependabot.yml
.github/workflows/codeql.yml
.github/workflows/dependabot-reviewer.yml
.github/workflows/maven_ci.yml

UF-6728: Add autoreview

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-graylog/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

Release 1.38

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-4.3.0

PR for release  release-4.3.0

---

.github/CODEOWNERS
dept44-build-tools/src/test/java/se/sundsvall/dept44/maven/mojo/CheckDockerImageNameMojoTest.java
dept44-build-tools/src/test/java/se/sundsvall/dept44/maven/mojo/CheckTruststoreValidityMojoTest.java
dept44-common-validators/src/test/java/se/sundsvall/dept44/common/validators/annotation/impl/AbstractValidatorTest.java
dept44-example/src/integration-test/java/se/sundsvall/petinventory/apptest/Constants.java
dept44-example/src/integration-test/java/se/sundsvall/petinventory/apptest/PetInventoryIT.java
dept44-example/src/main/java/se/sundsvall/petinventory/api/PetInventoryResource.java
dept44-example/src/test/java/se/sundsvall/petinventory/api/PetInventoryResourceTest.java
dept44-starter/src/main/java/se/sundsvall/dept44/configuration/LogbookConfiguration.java
dept44-starter/src/test/java/se/sundsvall/dept44/CertificateTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/BodyFilterPropertiesTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/ConstantsTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/NamedLoggerHttpLogWriterTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/ObjectMapperConfigurationTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/OpenApiConfigurationTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/SecurityConfigurationTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/TruststoreConfigurationTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/WebConfigurationTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/WebFluxConfigurationTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/security/TruststoreTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/support/BasicAuthenticationTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/util/ResourceUtilsTest.java

UF-7175: Use relative location header values + fix sonar issues

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-4.3.1

PR for release  release-4.3.1

---

dept44-starter-feign/src/main/java/se/sundsvall/dept44/configuration/feign/interceptor/OAuth2RequestInterceptor.java
dept44-starter-feign/src/test/java/se/sundsvall/dept44/configuration/feign/interceptor/OAuth2RequestInterceptorTest.java

UF-7997: Fix bug in feign oauth2 interceptor

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-5.0.0

PR for release  release-5.0.0

---

dept44-starter-test/src/main/java/se/sundsvall/dept44/test/AbstractAppTest.java
dept44-starter-test/src/test/java/se/sundsvall/dept44/test/AbstractAppTestTest.java

UF-8178: Added method for replacing matching string in request content

---

dept44-starter/src/main/java/se/sundsvall/dept44/configuration/LogbookConfiguration.java
dept44-starter/src/main/java/se/sundsvall/dept44/logbook/filter/ResponseFilterDefinition.java
dept44-starter/src/test/java/se/sundsvall/dept44/logbook/filter/ResponseFilterDefinitionTest.java

UF-8519: Remove binary data from logs, based on contentType.

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-5.0.1

PR for release  release-5.0.1

---

dept44-starter/src/main/resources/config/spring.properties

UF-8699: Add test context cache setting

---

dept44-starter/src/main/resources/config/application.properties

uf-8040: Default connect-timeout for hikari conection pool.

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-5.0.2

PR for release  release-5.0.2

---

dept44-starter/src/main/resources/config/spring.properties

UF-8951: Adjusted spring.test.context.cache.maxSize to a minimum

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-5.1.0

PR for release  release-5.1.0

---

dept44-starter/src/main/java/se/sundsvall/dept44/configuration/WebConfiguration.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/WebConfigurationTest.java

Adds a municipality id interceptor that checks if an 'allowed-municipality' property is set. If it is, it extracts the municipality id from the request path and verifies that it is allowed, if it is not set, all municipality ids are allowed.

MunicipalityId Interceptor

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.0

PR for release  release-6.0.0

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.1

PR for release  release-6.0.1

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.2

PR for release  release-6.0.2

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-formatting-plugin/src/main/resources/config.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

UF-10678: Adjusted formatting template to be compatible with release flow

---

README.md
dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-formatting-plugin/README.md
dept44-formatting-plugin/pom.xml
dept44-formatting-plugin/src/main/java/se/sundsvall/dept44/AbstractFormatMojo.java
dept44-formatting-plugin/src/main/java/se/sundsvall/dept44/ApplyFormatMojo.java
dept44-formatting-plugin/src/main/java/se/sundsvall/dept44/CheckFormatMojo.java
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-parent/pom.xml
pom.xml

UF-10693: Make formatting-plugin use parent and modify dept44 to work with that setup

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.3

PR for release  release-6.0.3

---

dept44-formatting-plugin/pom.xml
dept44-formatting-plugin/src/main/resources/config.xml

UF-10724: Remove problematic and redudant indent step in java formatting

---

dept44-example/src/integration-test/resources/EndpointsIT/__files/test01_apiDocs/response.json
dept44-example/src/integration-test/resources/EndpointsIT/__files/test02_health/response.json
dept44-example/src/integration-test/resources/EndpointsIT/__files/test03_info/response.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test01_getPetInventoryList/mappings/api-gateway-token.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test01_getPetInventoryList/mappings/api-petstore-pets.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test01_getPetInventoryList/response.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test02_getPetInventoryItem/mappings/api-gateway-token.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test02_getPetInventoryItem/mappings/api-petstore-pet.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test02_getPetInventoryItem/response.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test03_getPetInventoryItemNotFound/mappings/api-gateway-token.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test03_getPetInventoryItemNotFound/mappings/api-petstore-pet.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test04_getPetInventoryItemSomethingWentWrong/mappings/api-gateway-token.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test04_getPetInventoryItemSomethingWentWrong/mappings/api-petstore-pet.json
dept44-formatting-plugin/src/main/resources/config.xml
dept44-starter/src/test/resources/json-path-filter.expected.json
dept44-starter/src/test/resources/json-path-filter.input.json

UF-11007: Changed Spotless JSON-formatter to gson.

---

dept44-formatting-plugin/src/main/java/se/sundsvall/dept44/AbstractFormatMojo.java
dept44-formatting-plugin/src/main/resources/config.xml

This introduces the possibility to exclude and include files from spotless.
To use this you simply declare it in the pom.xml of the child project like this.
```xml
<plugin>
<groupId>se.sundsvall.dept44</groupId>
<artifactId>dept44-formatting-plugin</artifactId>
<configuration>
<javaExcludes>
<exclude>**/api/**</exclude>
<exclude>**/db/**</exclude>
</javaExcludes>
<jsonExcludes>
<exclude>**/*.json</exclude>
</jsonExcludes>
<sqlExcludes>
<exclude>**/*.sql</exclude>
</sqlExcludes>
<markdownExcludes>
<exclude>**/*.md</exclude>
</markdownExcludes>
<pomExcludes>
<exclude>**/*.xml</exclude>
</pomExcludes>
<javaIncludes>
<include>**/api/**</include>
<include>**/db/**</include>
</javaIncludes>
<jsonIncludes>
<include>**/*.json</include>
</jsonIncludes>
<sqlIncludes>
<include>**/*.sql</include> …
```

UF-11243: Enable file exclusions in dept44-formatting plugin

---

dept44-formatting-plugin/README.md

UF-11244: Update dept44-formatting plugin readme

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.4

PR for release  release-6.0.4

---

dept44-example/src/integration-test/java/se/sundsvall/petinventory/apptest/PetInventoryCircuitBreakerIT.java
dept44-example/src/integration-test/resources/PetInventoryCircuitBreakerIT/__files/test01_triggerCircuitBreaker/circuitbreaker-open-response.json
dept44-example/src/integration-test/resources/PetInventoryCircuitBreakerIT/__files/test01_triggerCircuitBreaker/error-response.json
dept44-example/src/integration-test/resources/PetInventoryCircuitBreakerIT/__files/test01_triggerCircuitBreaker/health-ok-response.json
dept44-example/src/integration-test/resources/PetInventoryCircuitBreakerIT/__files/test01_triggerCircuitBreaker/health-restricted-response.json
dept44-example/src/integration-test/resources/PetInventoryCircuitBreakerIT/__files/test01_triggerCircuitBreaker/mappings/api-gateway-token.json
dept44-example/src/integration-test/resources/PetInventoryCircuitBreakerIT/__files/test01_triggerCircuitBreaker/mappings/api-petstore-pets.json
dept44-example/src/main/java/se/sundsvall/petinventory/integration/petstore/PetStoreClient.java

UF-11349: Add apptests for circuitbreaker and health indicator.

---

dept44-example/src/integration-test/java/se/sundsvall/petinventory/apptest/EndpointsIT.java
dept44-example/src/integration-test/resources/EndpointsIT/__files/test01_apiDocs/response.json

UF-11659: Fix faulty test

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-scheduler/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.6

PR for release  release-6.0.6

---

dept44-starter-scheduler/README.md

UF-11664: Update README.md

---

dept44-starter/src/main/java/se/sundsvall/dept44/configuration/LogbookConfiguration.java
dept44-starter/src/main/java/se/sundsvall/dept44/logbook/filter/BodyFilterProvider.java

uf-11333: Add possibility to truncate payloads

---

dept44-starter-scheduler/README.md
dept44-starter-scheduler/src/main/java/se/sundsvall/dept44/scheduling/Dept44Scheduled.java
dept44-starter-scheduler/src/main/java/se/sundsvall/dept44/scheduling/Dept44SchedulerAspect.java
dept44-starter-scheduler/src/test/java/se/sundsvall/dept44/scheduling/Dept44SchedulerAspectTest.java

UF-11681: dept44-scheduler: Change maximumExecutionTime to string 

---

dept44-example/src/integration-test/resources/EndpointsIT/__files/test02_health/response.json
dept44-example/src/main/java/se/sundsvall/petinventory/service/scheduler/PetScheduler.java
dept44-example/src/main/resources/application.yml
dept44-starter-scheduler/src/main/java/se/sundsvall/dept44/scheduling/Dept44SchedulerAspect.java
dept44-starter-scheduler/src/main/java/se/sundsvall/dept44/scheduling/health/Dept44HealthIndicator.java
dept44-starter-scheduler/src/test/java/se/sundsvall/dept44/scheduling/Dept44SchedulerAspectTest.java

UF-11707: dept44-scheduler: Update aspect to properly parse placeholders and remove unnecessary annotation on indicator class

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-scheduler/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.7

PR for release  release-6.0.7

---

dept44-example/src/main/java/se/sundsvall/petinventory/api/PetInventoryResource.java
dept44-models/src/test/java/se/sundsvall/dept44/models/api/paging/validation/impl/ValidSortByPropertyConstraintValidatorTest.java
dept44-starter-feign/src/test/java/se/sundsvall/dept44/configuration/feign/FeignMultiCustomizerTest.java
dept44-starter-test/src/test/java/se/sundsvall/dept44/test/AbstractAppTestTest.java
dept44-starter/src/main/java/se/sundsvall/dept44/configuration/OpenApiProperties.java
dept44-starter/src/test/java/se/sundsvall/dept44/support/BasicAuthenticationTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/util/DateUtilsTest.java

UF-14455: Fixed Sonar issues, etc.

---

dept44-starter/src/main/java/se/sundsvall/dept44/configuration/LogbookConfiguration.java

uf-14825: Truncate logs first in the logbook filter chain, if enabled.

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-scheduler/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.8

PR for release  release-6.0.8

---

dept44-example/src/integration-test/java/se/sundsvall/petinventory/apptest/PetInventoryIT.java
dept44-example/src/integration-test/resources/EndpointsIT/__files/test01_apiDocs/response.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test01_getPetInventoryList/response.json
dept44-example/src/integration-test/resources/PetInventoryIT/__files/test02_getPetInventoryItem/response.json
dept44-example/src/main/java/se/sundsvall/petinventory/api/model/PetInventoryItem.java
dept44-example/src/main/java/se/sundsvall/petinventory/service/mapper/PetInventoryMapper.java
dept44-example/src/test/java/se/sundsvall/petinventory/api/model/PetInventoryItemTest.java
dept44-example/src/test/java/se/sundsvall/petinventory/service/mapper/PetInventoryMapperTest.java
dept44-starter/pom.xml
dept44-starter/src/main/java/se/sundsvall/dept44/configuration/WebConfiguration.java
dept44-starter/src/main/java/se/sundsvall/dept44/support/Identifier.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/WebConfigurationTest.java
dept44-starter/src/test/java/se/sundsvall/dept44/support/IdentifierTest.java
pom.xml

UF-15775: Added new Identifier filter.

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-scheduler/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.9

PR for release  release-6.0.9

---

dept44-starter/src/main/java/se/sundsvall/dept44/configuration/WebConfiguration.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/WebConfigurationTest.java

UF-15968: Removed identifier from ThreadLocal after finished request

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-scheduler/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.10

PR for release  release-6.0.10

---

dept44-starter/src/main/resources/config/application.properties

UF-16208: Reduced connection-timeout to 2 seconds.

---

dept44-example/src/integration-test/java/se/sundsvall/petinventory/apptest/PetInventoryIT.java
dept44-starter/src/main/java/se/sundsvall/dept44/configuration/WebConfiguration.java
dept44-starter/src/test/java/se/sundsvall/dept44/configuration/WebConfigurationTest.java

UF-15781: Removed support for request header sentbyuser

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-scheduler/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml

Descriptions taken from `README.md`

UF-15991: Add required metadata as specified in the documentation

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-scheduler/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release  release-6.0.12

PR for release  release-6.0.12

---

dept44-example/src/integration-test/java/se/sundsvall/petinventory/apptest/PetSchedulerIT.java
dept44-example/src/main/java/se/sundsvall/petinventory/service/mapper/PetInventoryMapper.java
dept44-example/src/main/resources/application-it.yml

UF-17329: Changed testcontainer version

---

dept44-formatting-plugin/pom.xml
dept44-service-parent/pom.xml

UF-17343: Removed obsolete properties

---

dept44-build-tools/pom.xml
dept44-common-validators/pom.xml
dept44-example/pom.xml
dept44-formatting-plugin/pom.xml
dept44-models/pom.xml
dept44-service-parent/pom.xml
dept44-starter-authorization/pom.xml
dept44-starter-feign/pom.xml
dept44-starter-logback-logserver/pom.xml
dept44-starter-parent/pom.xml
dept44-starter-scheduler/pom.xml
dept44-starter-test/pom.xml
dept44-starter-webclient/pom.xml
dept44-starter-webservicetemplate/pom.xml
dept44-starter/pom.xml
pom.xml

PR for creating release release-6.0.14

PR for release release-6.0.14
